// Auto-extracted from chemsex.html — Sadar Hati shared area + PL data
window.SAHA_DATA = {
  PL_LIST: ["Aris", "Bayu Lesmana", "David", "Dedi", "Deni", "Dodik", "Eko", "Hanim", "Hendra (KL-MLG)", "Husen", "Ibi", "Imam-Konselor", "Karyanto", "Maradona", "Nuri", "Paldi", "Reno", "Siswanto (KL-SBY)", "Sotong Hariyono"],
  wilayahData: {
    "Kota Malang": {
      "Blimbing": ["Arjosari", "Balearjosari", "Blimbing", "Bunulrejo", "Jodipan", "Kesatrian", "Pandanwangi", "Polehan", "Polowijen", "Purwantoro", "Purwodadi"],
      "Kedungkandang": ["Arjowinangun", "Bumiayu", "Buring", "Cemorokandang", "Kedungkandang", "Kotalama", "Lesanpuro", "Madyopuro", "Mergosono", "Sawojajar", "Tlogowaru", "Wonokoyo"],
      "Klojen": ["Bareng", "Gadingasri", "Kasin", "Kauman", "Kesatrian", "Kiduldalem", "Klojen", "Oro-oro Dowo", "Penanggungan", "Rampal Celaket", "Samaan", "Sukoharjo"],
      "Lowokwaru": ["Dinoyo", "Jatimulyo", "Ketawanggede", "Lowokwaru", "Merjosari", "Mojolangu", "Sumbersari", "Tasikmadu", "Tlogomas", "Tulusrejo", "Tunggulwulung", "Tunjungsekar"],
      "Sukun": ["Bakalankrajan", "Bandulan", "Bandungrejosari", "Ciptomulyo", "Gadang", "Karangbesuki", "Kebonsari", "Mulyorejo", "Pisangcandi", "Sukun", "Tanjungrejo"]
    },
    "Kota Batu": {
      "Batu": ["Ngaglik", "Oro-Oro Ombo", "Pesanggrahan", "Sidomulyo", "Sisir", "Songgokerto", "Sumberejo", "Temas"],
      "Bumiaji": ["Bulukerto", "Bumiaji", "Giripurno", "Gunungsari", "Pandanrejo", "Punten", "Sumberbrantas", "Sumbergondo", "Tulungrejo"],
      "Junrejo": ["Beji", "Dadaprejo", "Junrejo", "Mojorejo", "Pendem", "Tlekung", "Torongrejo"]
    },
    "Kab Malang": {
      "Ampelgading": ["Argoyuwono", "Lebakharjo", "Mulyoasri", "Purwoharjo", "Simojayan", "Sonowangi", "Tamanasri", "Tamansatriyan", "Tirtomarto", "Tirtomoyo", "Wirotaman", "Purwodadi", "Tawangagung"],
      "Bantur": ["Bandungrejo", "Bantur", "Karangsari", "Pringgondani", "Rejoyoso", "Srigonco", "Sumberbening", "Wonokerto", "Wonorejo", "Rejosari"],
      "Bululawang": ["Bakalan", "Bululawang", "Gading", "Kasembon", "Krebet", "Krebet Senggrong", "Kuwolu", "Lumbangsari", "Pringu", "Sempalwadak", "Sudimoro", "Sukonolo", "Wandanpuro", "Bumirejo"],
      "Dampit": ["Amadanom", "Baturetno", "Bumirejo", "Dampit", "Jambangan", "Majangtengah", "Pamotan", "Pojok", "Rembun", "Srimulyo", "Sukodono", "Sumbersuko"],
      "Dau": ["Gading Kulon", "Kalisongo", "Karangwidoro", "Kucur", "Landungsari", "Mulyoagung", "Petungsewu", "Selorejo", "Sumbersekar", "Tegalweru"],
      "Donomulyo": ["Banjarejo", "Donomulyo", "Kedungsalam", "Mentaraman", "Purwodadi", "Purworejo", "Sumberoto", "Tempursari", "Tlogosari", "Tulungrejo"],
      "Gedangan": ["Gajahrejo", "Gedangan", "Girimulyo", "Kalipare", "Segaran", "Sidodadi", "Sindurejo", "Sumberejo", "Tumpakrejo"],
      "Gondanglegi": ["Bulupitu", "Ganjaran", "Gondanglegi Kulon", "Gondanglegi Wetan", "Kenongo", "Ketawang", "Panggungrejo", "Putat Kidul", "Putat Lor", "Putukrejo", "Sepanjang", "Sukorejo", "Sukosari", "Urek-urek"],
      "Jabung": ["Argosari", "Boro Rejo", "Gadingkembar", "Gunungjati", "Jabung", "Kemantren", "Kemiri", "Ngadirejo", "Pandansari Lor", "Sidomulyo", "Sidorejo", "Slamparejo", "Sukolilo", "Sukopuro", "Taji"],
      "Kalipare": ["Arjosari", "Arjowilangun", "Kalipare", "Kaliasri", "Kalirejo", "Putukrejo", "Sumberpetung", "Tumpakrejo"],
      "Karangploso": ["Ampeldento", "Bocek", "Donowarih", "Girimoyo", "Kepuharjo", "Ngenep", "Ngijo", "Tawangargo", "Tegalgondo"],
      "Kasembon": ["Bayem", "Kasembon", "Pait", "Pondokagung", "Sukosari", "Wonoagung"],
      "Kepanjen": ["Ardirejo", "Cepokomulyo", "Curungrejo", "Dilem", "Jatirejoyoso", "Jenggolo", "Kedungpedaringan", "Kepanjen", "Mangunrejo", "Mojosari", "Ngadilangkung", "Panggungrejo", "Panggungsari", "Sengguruh", "Sukoraharjo", "Talangagung", "Tegalsari"],
      "Kromengan": ["Jambuwer", "Jatikerto", "Karangrejo", "Kromengan", "Ngadirejo", "Ngajum", "Peniwen", "Slorok"],
      "Lawang": ["Bedali", "Kalirejo", "Ketindan", "Lawang", "Mulyoarjo", "Sidodadi", "Sidoluhur", "Srigading", "Sumberngepoh", "Sumberporong", "Turirejo", "Wonorejo"],
      "Ngajum": ["Balesari", "Banjarsari", "Kesamben", "Kranggan", "Maguan", "Ngajum", "Ngasem", "Palaan"],
      "Ngantang": ["Banjarejo", "Banturejo", "Jombok", "Kaumrejo", "Mulyorejo", "Ngantru", "Pagersari", "Pandansari", "Purworejo", "Sidodadi", "Sumberagung", "Tulungrejo", "Waturejo"],
      "Pagak": ["Gampingan", "Pagak", "Pandanrejo", "Sempol", "Sumbermanjing Kulon", "Sumberkerto", "Sumberrejo", "Tlogorejo"],
      "Pagelaran": ["Balearjo", "Banjarejo", "Brongkal", "Clumprit", "Kademangan", "Kanigoro", "Karangsuko", "Pagelaran", "Sidorejo", "Suwaru"],
      "Pakis": ["Ampeldento", "Asrikaton", "Banjarejo", "Bunutwetan", "Kedungrejo", "Mangliawan", "Pakis Jajar", "Pakis Kembar", "Pucangsongo", "Sekarpuro", "Sukoanyar", "Sumberkradenan", "Sumberpasir", "Tirtomoyo", "Tirtomoyo"],
      "Pakisaji": ["Genengan", "Glanggang", "Jatisari", "Karangduren", "Karangpandan", "Kebonagung", "Kendalpayak", "Pakisaji", "Permanu", "Sutojayan", "Wadung", "Wonokerso"],
      "Poncokusumo": ["Argosuko", "Belung", "Dawuhan", "Gubugklakah", "Jambesari", "Karangnongko", "Karanganyar", "Ngadireso", "Ngadas", "Ngebruk", "Pajaran", "Pandansari", "Poncokusumo", "Sumber", "Wonomulyo", "Wonorejo", "Wringinanom"],
      "Pujon": ["Bendosari", "Madiredo", "Ngabab", "Ngroto", "Pandesari", "Pujon Kidul", "Pujon Lor", "Sukomulyo", "Tawangsari", "Wiyurejo"],
      "Singosari": ["Ardimulyo", "Baturetno", "Candirenggo", "Dengkol", "Gunungrejo", "Klampok", "Langlang", "Purwoasri", "Randuagung", "Singosari", "Tamanharjo", "Tunjungtirto", "Watugede", "Wonorejo"],
      "Sumbermanjing Wetan": ["Argotirto", "Druju", "Harjokuncaran", "Klepu", "Kedungbanteng", "Ringinkembar", "Ringinsari", "Sekarbanyu", "Sidoasri", "Sitiarjo", "Sumberagung", "Sumbermanjing Kulon", "Sumbermanjing Wetan", "Tambakasri", "Tambakrejo"],
      "Sumberpucung": ["Jatiguwi", "Karangkates", "Ngebruk", "Sambigede", "Senggreng", "Sumberpucung", "Ternyang"],
      "Tajinan": ["Gunungronggo", "Gunungsari", "Jambearjo", "Jatisari", "Ngawonggo", "Pandanmulyo", "Purwosekar", "Randugading", "Sumbersuko", "Tajinan", "Tangkilsari"],
      "Tirtoyudo": ["Ampelgading", "Gadungsari", "Jogomulyan", "Kepatihan", "Pujiharjo", "Purwodadi", "Sukorejo", "Sumbertangkil", "Tamankuncaran", "Tirtoyudo", "Tlogosari", "Wonoagung"],
      "Tumpang": ["Benjor", "Bokor", "Duwet", "Duwet Krajan", "Jeru", "Kambingan", "Kidal", "Malangsuko", "Ngingit", "Pandanajeng", "Pulungdowo", "Slamet", "Tulusbesar", "Tumpang", "Wringinsongo"],
      "Turen": ["Gedog Kulon", "Gedog Wetan", "Jeru", "Kedok", "Kemulan", "Pagedangan", "Sanankerto", "Sananrejo", "Sawahan", "Sedayu", "Sitiarjo", "Talok", "Tanggung", "Tawangrejeni", "Tumpakrejo", "Turen", "Undaan"],
      "Wagir": ["Dalisodo", "Gondowangi", "Jedong", "Mendalanwangi", "Pandanlandung", "Pandanrejo", "Parangargo", "Petungsewu", "Sidorahayu", "Sitirejo", "Sukodadi", "Sumbersuko"],
      "Wajak": ["Bambang", "Blayu", "Codo", "Dadapan", "Kidangbang", "Ngembal", "Patokpicis", "Sukoanyar", "Sukolilo", "Sumberputih", "Wajak", "Wonoayu"],
      "Wonosari": ["Bangelan", "Kebobang", "Kluwut", "Plaosan", "Plandi", "Sumberdem", "Sumberkembar", "Sumbertempur", "Wonosari"]
    },
    "Kab Pasuruan": {
      "Bangil": ["Bangil", "Dermo", "Gempeng", "Kalianyar", "Kalirejo", "Kauman", "Kersikan", "Kidul Dalem", "Kolursari", "Latek", "Manaruwi", "Masangan", "Pogar", "Raci", "Tambakan", "Wonorejo"],
      "Beji": ["Baujeng", "Beji", "Cangkringmalang", "Glanggang", "Gunung Sari", "Kedungboto", "Kedungringin", "Ngembe", "Pagak", "Sidowayah", "Sladi", "Wonokoyo"],
      "Gempol": ["Bulusari", "Carat", "Gempol", "Jeruk Purut", "Kejapanan", "Kepulungan", "Legok", "Ngerong", "Randupitu", "Sumbersuko", "Wonosari", "Winong"],
      "Gondangwetan": ["Bayeman", "Brambang", "Gayam", "Gondangrejo", "Gondangwetan", "Kaligung", "Karangsentul", "Keboncandi", "Kebonsari", "Ranggeh", "Sekarputih", "Tebas", "Tenggilis Rejo", "Wonojati"],
      "Grati": ["Cukurgondang", "Grati Tunon", "Kambingan Rejo", "Karanglo", "Kedawung Kulon", "Kedawung Wetan", "Kalipang", "Karangkliwon", "Krobokan Kidul", "Plososari", "Rebalas", "Sumberagung", "Sumberdawe", "Trewung"],
      "Kejayan": ["Ambal-Ambil", "Kayukebek", "Kedemungan", "Kedung Pengaron", "Kejayan", "Klinter", "Kurung", "Linggo", "Luwuk", "Oro-Oro Pule", "Pacar Keling", "Patebon", "Pengarengan", "Pukul", "Randu Gong", "Ranggeh", "Sladi", "Sumber Suko", "Tanggulangin", "Tundosoro", "Wangkal Kejayan", "Wonosari"],
      "Kraton": ["Bendungan", "Curah Dukuh", "Dhompo", "Gambir Kuning", "Jeruk", "Kalirejo", "Karanganyar", "Klampisrejo", "Kraton", "Ngabar", "Pukul", "Rejosari", "Selotambak", "Semare", "Sidogiri", "Tambakrejo", "Tambaksari", "Tampung", "Wonorejo"],
      "Lekok": ["Alastlogo", "Balunganyar", "Branang", "Gejugjati", "Jatirejo", "Pasinan", "Semedusari", "Tampung", "Tambakan", "Wates"],
      "Lumbang": ["Bulukandang", "Cukurgondang", "Karangasem", "Kronto", "Lumbang", "Panditan", "Pancur", "Wangunsari", "Watuprapat", "Welulang"],
      "Nguling": ["Dandanggendis", "Kapasan", "Kedawang", "Mlaten", "Nguling", "Randusari", "Sanganom", "Sedarum", "Sudimulyo", "Sumberanyar", "Watestani", "Watuprapat", "Wotgalih"],
      "Pandaan": ["Banjarkejen", "Banjarsari", "Durensewu", "Jogosari", "Karangjati", "Kutorejo", "Pandaan", "Petir", "Plintahan", "Sebani", "Sumbergedang", "Sumberrejo", "Tawangrejo", "Wonokoyo"],
      "Pasrepan": ["Ampelsari", "Galih", "Jogorepuh", "Klakah", "Lemahbang", "Mangguan", "Pasrepan", "Petung", "Pohgading", "Pusung Malang", "Rejosari", "Sapulante", "Sibon", "Sudimulyo", "Tempuran", "Terkuni", "Tlogorejo", "Wonorejo"],
      "Pohjentrek": ["Kertosari", "Parasrejo", "Pleret", "Pohjentrek", "Sukorejo", "Sungikulon", "Sungiwetan", "Susukanrejo", "Tidu", "Warungdowo"],
      "Prigen": ["Bulukandang", "Candiwates", "Dayurejo", "Gambiran", "Jatiarjo", "Ketanireng", "Ledug", "Lumbangrejo", "Pecalukan", "Prigen", "Sekargadung", "Sukoreno", "Sukolilo"],
      "Purwodadi": ["Cowek", "Dawuhansengon", "Gerbo", "Jatisari", "Kayukebek", "Parerejo", "Purwodadi", "Purwosari", "Semut", "Sentul", "Sukolilo", "Tambaksari"],
      "Purwosari": ["Bakalan", "Cendono", "Karangrejo", "Kayoman", "Martopuro", "Pucangsari", "Purwosari", "Sekarmojo", "Semut", "Sengonagung", "Sumberrejo", "Tejowangi", "Tenggilis Rejo"],
      "Puspo": ["Jimbaran", "Keduwung", "Kemiri", "Palangsari", "Pusung Malang", "Puspo", "Puspoagung", "Puspojati", "Sumberpitu"],
      "Rejoso": ["Arjosari", "Jarangan", "Jeladri", "Kawisrejo", "Ketegan", "Kalirejo", "Kedungbako", "Manikrejo", "Patuguran", "Rejoso Kidul", "Rejoso Lor", "Sadengrejo", "Segoropuro", "Sekarmojo", "Toyaning"],
      "Rembang": ["Genengwaru", "Kalisat", "Kanigoro", "Krengih", "Mojoparon", "Orobulu", "Oro Oro Ombo Kulon", "Oro Oro Ombo Wetan", "Pajaran", "Pekoren", "Rembang", "Sumberglagah", "Tampung", "Tempuran", "Tampung", "Tokol"],
      "Sukorejo": ["Candibinangun", "Curahrejo", "Dukuhsari", "Glagahsari", "Gunting", "Kalirejo", "Kaligintung", "Kandangrejo", "Kepulungan", "Ngadimulyo", "Ngadiwono", "Pakukerto", "Sebandung", "Sukorejo", "Suwayuwo", "Wonokerto"],
      "Tosari": ["Baledono", "Kandangan", "Keduwung", "Mororejo", "Ngadiwono", "Podokoyo", "Sedaeng", "Tosari", "Wonokitri", "Wonokerto"],
      "Tutur": ["Andonosari", "Blarang", "Gendro", "Kalipucang", "Kayukebek", "Ngadirejo", "Ngembal", "Ngerong", "Pungging", "Tlogosari", "Tutur", "Wonosari"],
      "Winongan": ["Bandaran", "Gadingsari", "Jeladri", "Kadenrejo", "Karangtengah", "Kedungrejo", "Menyarik", "Minggir", "Mendalan", "Prodo", "Sruwi", "Sumberrejo", "Tenggilis Rejo", "Umbulan", "Winongan Kidul", "Winongan Lor"],
      "Wonorejo": ["Cobanjoyo", "Jatigunting", "Karangasem", "Karangjati", "Kejayan", "Kendang Dukuh", "Kluwut", "Rebono", "Sambisirah", "Sladi", "Sugihwaras", "Sukorame", "Wonorejo"]
    }
  }
};
